# name: Build and Push to ECR

# on:
#   push:
#     branches: [main, master, develop]
#   workflow_dispatch: # Allow manual trigger from GitHub UI

# env:
#   AWS_REGION: us-east-1
#   ECR_REGISTRY: 672508880349.dkr.ecr.us-east-1.amazonaws.com
#   ECR_REPOSITORY: tech-challenge-2

# jobs:
#   build-and-push:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Build and push Docker image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           echo "Building Docker image..."
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

#           echo "Pushing Docker image to ECR..."
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

#           echo "✅ Successfully pushed images:"
#           echo "📦 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
#           echo "📦 $ECR_REGISTRY/$ECR_REPOSITORY:latest"
